version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: hrms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeMeStrong}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:${POSTGRES_PASSWORD:-changeMeStrong}@db:5432/hrms_db}
      API_HOST: ${API_HOST:-0.0.0.0}
      API_PORT: ${API_PORT:-8000}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    depends_on:
      - db
    ports:
      - "${PUBLIC_PORT:-8081}:8000"
    networks:
      - appnet
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  appnet:
    driver: bridge
